### ISSUE TITLE
Bug: Show ボタンと New Topic ボタンが動作しない

### ISSUE THREAD

**Issue by ghost** [S-H-GAMELINKS/TootGetter#1]
![image](https://user-images.githubusercontent.com/2155555/48238032-c6273980-e40c-11e8-9da6-2e44bc6f4e92.png)

**Comment by ghost** [comment]
Chrome だと動いているようだ。

**Comment by S-H-GAMELINKS** [comment]
Chromeでしか確認していたので、気付かなかったようですね

ちょっとコードを見てきます

**Comment by S-H-GAMELINKS** [comment]
Edgeでも動いているようです

**Comment by S-H-GAMELINKS** [comment]
Chrome の開発ツールでかくにんしたところ以下のエラーを発見

```
Uncaught ReferenceError: Macy is not defined
```
